// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#include "../ui.h"

void ui_LoadScreen_screen_init(void)
{
    ui_LoadScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoadScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button4, 136);
    lv_obj_set_height(ui_Button4, 62);
    lv_obj_set_x(ui_Button4, 322);
    lv_obj_set_y(ui_Button4, 194);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Button4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Return");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_LoadScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, -190);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Send CAN Message");

    ui_TextArea2 = lv_textarea_create(ui_LoadScreen);
    lv_obj_set_width(ui_TextArea2, 510);
    lv_obj_set_height(ui_TextArea2, 190);
    lv_obj_set_x(ui_TextArea2, -100);
    lv_obj_set_y(ui_TextArea2, 90);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    ui_Label10 = lv_label_create(ui_LoadScreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -310);
    lv_obj_set_y(ui_Label10, -140);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "ID");

    ui_Label11 = lv_label_create(ui_LoadScreen);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -310);
    lv_obj_set_y(ui_Label11, -80);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Intervall");

    ui_Button7 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button7, 70);
    lv_obj_set_height(ui_Button7, 45);
    lv_obj_set_x(ui_Button7, 140);
    lv_obj_set_y(ui_Button7, -140);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_CLICKED, NULL);

    ui_Label12 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -1);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "UP");

    ui_Button9 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button9, 70);
    lv_obj_set_height(ui_Button9, 45);
    lv_obj_set_x(ui_Button9, 230);
    lv_obj_set_y(ui_Button9, -140);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_CLICKED, NULL);

    ui_Label14 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -1);
    lv_obj_set_y(ui_Label14, 1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "DOWN");

    ui_Button8 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button8, 70);
    lv_obj_set_height(ui_Button8, 45);
    lv_obj_set_x(ui_Button8, 140);
    lv_obj_set_y(ui_Button8, -80);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_CLICKED, NULL);

    ui_Label13 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 1);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "UP");

    ui_Button10 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button10, 70);
    lv_obj_set_height(ui_Button10, 45);
    lv_obj_set_x(ui_Button10, 230);
    lv_obj_set_y(ui_Button10, -80);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_CLICKED, NULL);

    ui_Label15 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 1);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "DOWN");

    ui_Button11 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button11, 140);
    lv_obj_set_height(ui_Button11, 90);
    lv_obj_set_x(ui_Button11, 260);
    lv_obj_set_y(ui_Button11, 40);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_CLICKED, NULL);

    ui_Label16 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, 1);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Send");
   
    ui_Panel3 = lv_obj_create(ui_LoadScreen);
    lv_obj_set_width(ui_Panel3, 250);
    lv_obj_set_height(ui_Panel3, 35);
    lv_obj_set_x(ui_Panel3, -110);
    lv_obj_set_y(ui_Panel3, -140);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, 1);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "0x001");

    ui_Panel4 = lv_obj_create(ui_LoadScreen);
    lv_obj_set_width(ui_Panel4, 250);
    lv_obj_set_height(ui_Panel4, 35);
    lv_obj_set_x(ui_Panel4, -110);
    lv_obj_set_y(ui_Panel4, -80);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, 1);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "1000 ms");

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
