// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#include "../ui.h"

void ui_LoadScreen_screen_init(void)
{
    ui_LoadScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoadScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button4, 136);
    lv_obj_set_height(ui_Button4, 62);
    lv_obj_set_x(ui_Button4, 322);
    lv_obj_set_y(ui_Button4, 194);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Button4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Return");
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_LoadScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, -211);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Send CAN Message");

    ui_TextArea2 = lv_textarea_create(ui_LoadScreen);
    lv_obj_set_width(ui_TextArea2, 511);
    lv_obj_set_height(ui_TextArea2, 123);
    lv_obj_set_x(ui_TextArea2, -99);
    lv_obj_set_y(ui_TextArea2, 33);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");



    ui_Label10 = lv_label_create(ui_LoadScreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -312);
    lv_obj_set_y(ui_Label10, -140);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "ID");

    ui_Label11 = lv_label_create(ui_LoadScreen);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -310);
    lv_obj_set_y(ui_Label11, -98);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Time");

    ui_Button7 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button7, 59);
    lv_obj_set_height(ui_Button7, 34);
    lv_obj_set_x(ui_Button7, 145);
    lv_obj_set_y(ui_Button7, -137);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);

    ui_Label12 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -1);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "UP");

    ui_Button9 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button9, 60);
    lv_obj_set_height(ui_Button9, 35);
    lv_obj_set_x(ui_Button9, 229);
    lv_obj_set_y(ui_Button9, -139);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);

    ui_Label14 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -1);
    lv_obj_set_y(ui_Label14, 1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "DOWN");

    ui_Button8 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button8, 56);
    lv_obj_set_height(ui_Button8, 33);
    lv_obj_set_x(ui_Button8, 145);
    lv_obj_set_y(ui_Button8, -76);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);

    ui_Label13 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 1);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "UP");

    ui_Button10 = lv_btn_create(ui_LoadScreen);
    lv_obj_set_width(ui_Button10, 62);
    lv_obj_set_height(ui_Button10, 33);
    lv_obj_set_x(ui_Button10, 228);
    lv_obj_set_y(ui_Button10, -76);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);

    ui_Label15 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 2);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "DOWN");

    ui_Panel3 = lv_obj_create(ui_LoadScreen);
    lv_obj_set_width(ui_Panel3, 251);
    lv_obj_set_height(ui_Panel3, 34);
    lv_obj_set_x(ui_Panel3, -110);
    lv_obj_set_y(ui_Panel3, -138);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_LoadScreen);
    lv_obj_set_width(ui_Panel4, 244);
    lv_obj_set_height(ui_Panel4, 32);
    lv_obj_set_x(ui_Panel4, -114);
    lv_obj_set_y(ui_Panel4, -76);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
