// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#include "../ui.h"

lv_chart_series_t * ui_chart_series = NULL; // Definition der globalen Variable


void ui_TopScreen_screen_init(void)
{
    ui_TopScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TopScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_TopScreen);
    lv_obj_set_width(ui_Button3, 136);
    lv_obj_set_height(ui_Button3, 62);
    lv_obj_set_x(ui_Button3, 322);
    lv_obj_set_y(ui_Button3, 194);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Button3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Return");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_TopScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -1);
    lv_obj_set_y(ui_Label5, -211);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Top CAN Packeges");

    ui_Chart1 = lv_chart_create(ui_TopScreen);
    lv_obj_set_width(ui_Chart1, 445);
    lv_obj_set_height(ui_Chart1, 240);
    lv_obj_set_x(ui_Chart1, -80);
    lv_obj_set_y(ui_Chart1, -37);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_BAR);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 1, true, 50);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 100); // X-Achse: Häufigkeit

    // Datenreihe hinzufügen
    ui_chart_series = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_X);

    // Y-Achsen-Labels erstellen
    for (int i = 0; i < 10; i++) {
        lv_obj_t * label = lv_label_create(ui_TopScreen);
        lv_obj_set_width(label, LV_SIZE_CONTENT);
        lv_obj_set_height(label, LV_SIZE_CONTENT);
        lv_obj_align_to(label, ui_Chart1, LV_ALIGN_OUT_LEFT_TOP, -10, 20 + i * 20); // Position links vom Diagramm
        lv_label_set_text_fmt(label, "CAN %d", i + 1); // Temporäre Labels, später dynamisch aktualisieren
    }



    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Chart1, ui_event_Chart1, LV_EVENT_ALL, NULL);

}
