// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#ifndef _WAVESHARE43_MINIMAL_UI_H
#define _WAVESHARE43_MINIMAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES
void update_diagram(void);

// SCREEN: ui_TraceScreen
void ui_TraceScreen_screen_init(void);
extern lv_obj_t * ui_TraceScreen;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_TopScreen
void ui_TopScreen_screen_init(void);
extern lv_obj_t * ui_TopScreen;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
void ui_event_Chart1(lv_event_t * e);
extern lv_obj_t * ui_Chart1;
extern lv_chart_series_t * ui_chart_series_1; // Datenreihe des Diagramms

// CUSTOM VARIABLES

// SCREEN: ui_LoadScreen
void ui_LoadScreen_screen_init(void);
extern lv_obj_t * ui_LoadScreen;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label12;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label14;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label13;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label15;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label16;
//extern lv_obj_t * ui_Label17;
//extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
// CUSTOM VARIABLES
void id_up_handler();
void id_down_handler();
void interval_up_handler();
void interval_down_handler();
void send_start_handler();
// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
