// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#include "ui.h"

void show_current_can_messages(lv_event_t * e)
{
	// Your code here
}

void update_can_statistics(lv_event_t * e)
{
	// Your code here
}
