// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: waveshare43-minimal

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void show_current_can_messages(lv_event_t * e);
void update_can_statistics(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
